using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;
using GameClient.Managers;

namespace GameClient.UI
{
    public class BattleHeroDragItem : MonoBehaviour, IBeginDragHandler, IDragHandler, IEndDragHandler
    {
        public long HeroId { get; private set; }
        public bool IsOnBoard { get; private set; }
        public int BoardPosition { get; private set; } = -1;

        private Canvas _canvas;
        private RectTransform _rectTransform;
        private CanvasGroup _canvasGroup;
        private Vector3 _startPosition;
        private Transform _originalParent;
        private BattlePrepPanel _panel;

        public void Setup(long heroId, bool isOnBoard, int boardPosition, BattlePrepPanel panel)
        {
            HeroId = heroId;
            IsOnBoard = isOnBoard;
            BoardPosition = boardPosition;
            _panel = panel;

            _rectTransform = GetComponent<RectTransform>();
            _canvas = GetComponentInParent<Canvas>();
            
            _canvasGroup = GetComponent<CanvasGroup>();
            if (_canvasGroup == null)
            {
                _canvasGroup = gameObject.AddComponent<CanvasGroup>();
            }
        }

        public void OnBeginDrag(PointerEventData eventData)
        {
            if (_panel == null) return;

            // Rule: If dragging from owned list, but board already has 5 heroes, cancel drag
            if (!IsOnBoard && _panel.GetFormationCount() >= 5)
            {
                eventData.pointerDrag = null; // Cancel drag operation in Unity
                ToastManager.Instance.ShowNormalToast("Đội hình đã đủ 5 tướng! Kéo tướng xuống để thay thế.");
                return;
            }

            _startPosition = transform.position;
            _originalParent = transform.parent;

            // Move to canvas root so it renders on top of everything
            transform.SetParent(_canvas.transform, true);
            _canvasGroup.blocksRaycasts = false;
            _canvasGroup.alpha = 0.7f;
        }

        public void OnDrag(PointerEventData eventData)
        {
            Vector2 localPoint;
            Camera cam = (_canvas.renderMode == RenderMode.ScreenSpaceOverlay) ? null : _canvas.worldCamera;
            if (RectTransformUtility.ScreenPointToLocalPointInRectangle(_canvas.transform as RectTransform, eventData.position, cam, out localPoint))
            {
                _rectTransform.anchoredPosition = localPoint;
            }
        }

        public void OnEndDrag(PointerEventData eventData)
        {
            _canvasGroup.blocksRaycasts = true;
            _canvasGroup.alpha = 1f;

            // Check if dropped on a Slot or somewhere else
            GameObject dropTarget = eventData.pointerCurrentRaycast.gameObject;
            BattleFormationSlot slot = null;

            if (dropTarget != null)
            {
                slot = dropTarget.GetComponent<BattleFormationSlot>();
                if (slot == null)
                {
                    slot = dropTarget.GetComponentInParent<BattleFormationSlot>();
                }
            }

            if (slot != null)
            {
                // Dropped on a slot! Handle assignment/swap
                _panel.HandleHeroDroppedOnSlot(HeroId, slot.SlotIndex, IsOnBoard, BoardPosition);
                Destroy(gameObject); // Prefabs will be regenerated by BattlePrepPanel refresh
            }
            else
            {
                // Dropped outside a slot
                if (IsOnBoard)
                {
                    // Dragged from board to outside/down -> Remove hero from formation
                    _panel.RemoveHeroFromFormation(HeroId);
                }
                else
                {
                    // Dragged from owned list to outside -> Snap back
                    transform.SetParent(_originalParent, false);
                    transform.position = _startPosition;
                }
            }
        }
    }
}
