// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: world.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameClient.Network.Pb {

  /// <summary>Holder for reflection information generated from world.proto</summary>
  public static partial class WorldReflection {

    #region Descriptor
    /// <summary>File descriptor for world.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WorldReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgt3b3JsZC5wcm90bxICcGIaDGNvbW1vbi5wcm90bxoMcGxheWVyLnByb3Rv",
            "GgpzZWN0LnByb3RvGg5kaXNjaXBsZS5wcm90bxoKaXRlbS5wcm90bxoLZ2Fj",
            "aGEucHJvdG8aDW1pc3Npb24ucHJvdG8aDGNvbWJhdC5wcm90bxoMc3lzdGVt",
            "LnByb3RvMoMLCg5HYXRld2F5U2VydmljZRI7CgpHZXRWZXJzaW9uEhUucGIu",
            "R2V0VmVyc2lvblJlcXVlc3QaFi5wYi5HZXRWZXJzaW9uUmVzcG9uc2USMgoH",
            "R2V0QmFzZRISLnBiLkdldEJhc2VSZXF1ZXN0GhMucGIuR2V0QmFzZVJlc3Bv",
            "bnNlEkEKDENyZWF0ZVBsYXllchIXLnBiLkNyZWF0ZVBsYXllclJlcXVlc3Qa",
            "GC5wYi5DcmVhdGVQbGF5ZXJSZXNwb25zZRJNChBHZXRQbGF5ZXJQcm9maWxl",
            "EhsucGIuR2V0UGxheWVyUHJvZmlsZVJlcXVlc3QaHC5wYi5HZXRQbGF5ZXJQ",
            "cm9maWxlUmVzcG9uc2USMgoLR2V0U2VjdEluZm8SFS5wYi5HZXRQcm9maWxl",
            "UmVxdWVzdBoMLnBiLlNlY3RJbmZvEkoKD1VwZ3JhZGVCdWlsZGluZxIaLnBi",
            "LlVwZ3JhZGVCdWlsZGluZ1JlcXVlc3QaGy5wYi5VcGdyYWRlQnVpbGRpbmdS",
            "ZXNwb25zZRJNChBDb2xsZWN0UmVzb3VyY2VzEhsucGIuQ29sbGVjdFJlc291",
            "cmNlc1JlcXVlc3QaHC5wYi5Db2xsZWN0UmVzb3VyY2VzUmVzcG9uc2USQQoM",
            "U2F2ZUFkbWluTWFwEhcucGIuU2F2ZUFkbWluTWFwUmVxdWVzdBoYLnBiLlNh",
            "dmVBZG1pbk1hcFJlc3BvbnNlEkEKDEdldFBsYXllck1hcBIXLnBiLkdldFBs",
            "YXllck1hcFJlcXVlc3QaGC5wYi5HZXRQbGF5ZXJNYXBSZXNwb25zZRI4CglH",
            "ZXRIZXJvZXMSFC5wYi5HZXRIZXJvZXNSZXF1ZXN0GhUucGIuR2V0SGVyb2Vz",
            "UmVzcG9uc2USQQoMU2V0Rm9ybWF0aW9uEhcucGIuU2V0Rm9ybWF0aW9uUmVx",
            "dWVzdBoYLnBiLlNldEZvcm1hdGlvblJlc3BvbnNlEkoKD0xldmVsVXBEaXNj",
            "aXBsZRIaLnBiLkxldmVsVXBEaXNjaXBsZVJlcXVlc3QaGy5wYi5MZXZlbFVw",
            "RGlzY2lwbGVSZXNwb25zZRI+CgtMZXZlbFVwSGVybxIWLnBiLkxldmVsVXBI",
            "ZXJvUmVxdWVzdBoXLnBiLkxldmVsVXBIZXJvUmVzcG9uc2USQQoMQ2hlY2tJ",
            "bkRhaWx5EhcucGIuQ2hlY2tJbkRhaWx5UmVxdWVzdBoYLnBiLkNoZWNrSW5E",
            "YWlseVJlc3BvbnNlElMKEkNsYWltTWlzc2lvblJld2FyZBIdLnBiLkNsYWlt",
            "TWlzc2lvblJld2FyZFJlcXVlc3QaHi5wYi5DbGFpbU1pc3Npb25SZXdhcmRS",
            "ZXNwb25zZRJQChFWYWxpZGF0ZVB2RVJlc3VsdBIcLnBiLlZhbGlkYXRlUHZF",
            "UmVzdWx0UmVxdWVzdBodLnBiLlZhbGlkYXRlUHZFUmVzdWx0UmVzcG9uc2US",
            "NAoMR2V0SW52ZW50b3J5EhUucGIuR2V0UHJvZmlsZVJlcXVlc3QaDS5wYi5J",
            "bnZlbnRvcnkSMAoJRXF1aXBJdGVtEhAucGIuRXF1aXBSZXF1ZXN0GhEucGIu",
            "RXF1aXBSZXNwb25zZRJKCg9HZXRHYWNoYUJhbm5lcnMSGi5wYi5HZXRHYWNo",
            "YUJhbm5lcnNSZXF1ZXN0GhsucGIuR2V0R2FjaGFCYW5uZXJzUmVzcG9uc2US",
            "MgoHRG9HYWNoYRISLnBiLkRvR2FjaGFSZXF1ZXN0GhMucGIuRG9HYWNoYVJl",
            "c3BvbnNlEj4KC0dldE1pc3Npb25zEhYucGIuR2V0TWlzc2lvbnNSZXF1ZXN0",
            "GhcucGIuR2V0TWlzc2lvbnNSZXNwb25zZTL0AQoMV29ybGRTZXJ2aWNlEjIK",
            "EEludGVybmFsU3luY1NlY3QSDC5wYi5TZWN0SW5mbxoQLnBiLkJhc2VSZXNw",
            "b25zZRI8Cg1MaXN0Q3V0c2NlbmVzEhAucGIuRW1wdHlSZXF1ZXN0GhkucGIu",
            "TGlzdEN1dHNjZW5lc1Jlc3BvbnNlEjcKC0dldEN1dHNjZW5lEhYucGIuR2V0",
            "Q3V0c2NlbmVSZXF1ZXN0GhAucGIuQ3V0c2NlbmVEYXRhEjkKDFNhdmVDdXRz",
            "Y2VuZRIXLnBiLlNhdmVDdXRzY2VuZVJlcXVlc3QaEC5wYi5CYXNlUmVzcG9u",
            "c2VCKloQc2VydmVyL3BrZy9wYjtwYqoCFUdhbWVDbGllbnQuTmV0d29yay5Q",
            "YmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GameClient.Network.Pb.CommonReflection.Descriptor, global::GameClient.Network.Pb.PlayerReflection.Descriptor, global::GameClient.Network.Pb.SectReflection.Descriptor, global::GameClient.Network.Pb.DiscipleReflection.Descriptor, global::GameClient.Network.Pb.ItemReflection.Descriptor, global::GameClient.Network.Pb.GachaReflection.Descriptor, global::GameClient.Network.Pb.MissionReflection.Descriptor, global::GameClient.Network.Pb.CombatReflection.Descriptor, global::GameClient.Network.Pb.SystemReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
