// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: leaderboard.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCompletedStagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompletedStagesRequest) Reset() {
	*x = GetCompletedStagesRequest{}
	mi := &file_leaderboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompletedStagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompletedStagesRequest) ProtoMessage() {}

func (x *GetCompletedStagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompletedStagesRequest.ProtoReflect.Descriptor instead.
func (*GetCompletedStagesRequest) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{0}
}

type GetCompletedStagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	StageIds      []string               `protobuf:"bytes,2,rep,name=stage_ids,json=stageIds,proto3" json:"stage_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompletedStagesResponse) Reset() {
	*x = GetCompletedStagesResponse{}
	mi := &file_leaderboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompletedStagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompletedStagesResponse) ProtoMessage() {}

func (x *GetCompletedStagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompletedStagesResponse.ProtoReflect.Descriptor instead.
func (*GetCompletedStagesResponse) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{1}
}

func (x *GetCompletedStagesResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetCompletedStagesResponse) GetStageIds() []string {
	if x != nil {
		return x.StageIds
	}
	return nil
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int64                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Value         int64                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_leaderboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{2}
}

func (x *LeaderboardEntry) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardEntry) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *LeaderboardEntry) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "power" or "stage"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_leaderboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{3}
}

func (x *GetLeaderboardRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResponse) Reset() {
	*x = GetLeaderboardResponse{}
	mi := &file_leaderboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResponse) ProtoMessage() {}

func (x *GetLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{4}
}

func (x *GetLeaderboardResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetLeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_leaderboard_proto protoreflect.FileDescriptor

const file_leaderboard_proto_rawDesc = "" +
	"\n" +
	"\x11leaderboard.proto\x12\x02pb\x1a\fcommon.proto\"\x1b\n" +
	"\x19GetCompletedStagesRequest\"_\n" +
	"\x1aGetCompletedStagesResponse\x12$\n" +
	"\x04base\x18\x01 \x01(\v2\x10.pb.BaseResponseR\x04base\x12\x1b\n" +
	"\tstage_ids\x18\x02 \x03(\tR\bstageIds\"X\n" +
	"\x10LeaderboardEntry\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x03R\x04rank\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x03R\x05value\"+\n" +
	"\x15GetLeaderboardRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"n\n" +
	"\x16GetLeaderboardResponse\x12$\n" +
	"\x04base\x18\x01 \x01(\v2\x10.pb.BaseResponseR\x04base\x12.\n" +
	"\aentries\x18\x02 \x03(\v2\x14.pb.LeaderboardEntryR\aentriesB*Z\x10server/pkg/pb;pb\xaa\x02\x15GameClient.Network.Pbb\x06proto3"

var (
	file_leaderboard_proto_rawDescOnce sync.Once
	file_leaderboard_proto_rawDescData []byte
)

func file_leaderboard_proto_rawDescGZIP() []byte {
	file_leaderboard_proto_rawDescOnce.Do(func() {
		file_leaderboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leaderboard_proto_rawDesc), len(file_leaderboard_proto_rawDesc)))
	})
	return file_leaderboard_proto_rawDescData
}

var file_leaderboard_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_leaderboard_proto_goTypes = []any{
	(*GetCompletedStagesRequest)(nil),  // 0: pb.GetCompletedStagesRequest
	(*GetCompletedStagesResponse)(nil), // 1: pb.GetCompletedStagesResponse
	(*LeaderboardEntry)(nil),           // 2: pb.LeaderboardEntry
	(*GetLeaderboardRequest)(nil),      // 3: pb.GetLeaderboardRequest
	(*GetLeaderboardResponse)(nil),     // 4: pb.GetLeaderboardResponse
	(*BaseResponse)(nil),               // 5: pb.BaseResponse
}
var file_leaderboard_proto_depIdxs = []int32{
	5, // 0: pb.GetCompletedStagesResponse.base:type_name -> pb.BaseResponse
	5, // 1: pb.GetLeaderboardResponse.base:type_name -> pb.BaseResponse
	2, // 2: pb.GetLeaderboardResponse.entries:type_name -> pb.LeaderboardEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_leaderboard_proto_init() }
func file_leaderboard_proto_init() {
	if File_leaderboard_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leaderboard_proto_rawDesc), len(file_leaderboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_leaderboard_proto_goTypes,
		DependencyIndexes: file_leaderboard_proto_depIdxs,
		MessageInfos:      file_leaderboard_proto_msgTypes,
	}.Build()
	File_leaderboard_proto = out.File
	file_leaderboard_proto_goTypes = nil
	file_leaderboard_proto_depIdxs = nil
}
