// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0--rc1
// source: combat.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CombatService_ValidatePvEResult_FullMethodName = "/pb.CombatService/ValidatePvEResult"
)

// CombatServiceClient is the client API for CombatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CombatServiceClient interface {
	ValidatePvEResult(ctx context.Context, in *ValidatePvEResultRequest, opts ...grpc.CallOption) (*ValidatePvEResultResponse, error)
}

type combatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCombatServiceClient(cc grpc.ClientConnInterface) CombatServiceClient {
	return &combatServiceClient{cc}
}

func (c *combatServiceClient) ValidatePvEResult(ctx context.Context, in *ValidatePvEResultRequest, opts ...grpc.CallOption) (*ValidatePvEResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidatePvEResultResponse)
	err := c.cc.Invoke(ctx, CombatService_ValidatePvEResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CombatServiceServer is the server API for CombatService service.
// All implementations must embed UnimplementedCombatServiceServer
// for forward compatibility.
type CombatServiceServer interface {
	ValidatePvEResult(context.Context, *ValidatePvEResultRequest) (*ValidatePvEResultResponse, error)
	mustEmbedUnimplementedCombatServiceServer()
}

// UnimplementedCombatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCombatServiceServer struct{}

func (UnimplementedCombatServiceServer) ValidatePvEResult(context.Context, *ValidatePvEResultRequest) (*ValidatePvEResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidatePvEResult not implemented")
}
func (UnimplementedCombatServiceServer) mustEmbedUnimplementedCombatServiceServer() {}
func (UnimplementedCombatServiceServer) testEmbeddedByValue()                       {}

// UnsafeCombatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CombatServiceServer will
// result in compilation errors.
type UnsafeCombatServiceServer interface {
	mustEmbedUnimplementedCombatServiceServer()
}

func RegisterCombatServiceServer(s grpc.ServiceRegistrar, srv CombatServiceServer) {
	// If the following call panics, it indicates UnimplementedCombatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CombatService_ServiceDesc, srv)
}

func _CombatService_ValidatePvEResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatePvEResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CombatServiceServer).ValidatePvEResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CombatService_ValidatePvEResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CombatServiceServer).ValidatePvEResult(ctx, req.(*ValidatePvEResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CombatService_ServiceDesc is the grpc.ServiceDesc for CombatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CombatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CombatService",
	HandlerType: (*CombatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidatePvEResult",
			Handler:    _CombatService_ValidatePvEResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "combat.proto",
}
