// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: gacha.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GachaBanner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BannerId      int32                  `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"` // C# đang tìm .BannerId
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CostDiamond   int32                  `protobuf:"varint,4,opt,name=cost_diamond,json=costDiamond,proto3" json:"cost_diamond,omitempty"` // C# đang tìm .CostDiamond
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GachaBanner) Reset() {
	*x = GachaBanner{}
	mi := &file_gacha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GachaBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GachaBanner) ProtoMessage() {}

func (x *GachaBanner) ProtoReflect() protoreflect.Message {
	mi := &file_gacha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GachaBanner.ProtoReflect.Descriptor instead.
func (*GachaBanner) Descriptor() ([]byte, []int) {
	return file_gacha_proto_rawDescGZIP(), []int{0}
}

func (x *GachaBanner) GetBannerId() int32 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

func (x *GachaBanner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GachaBanner) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GachaBanner) GetCostDiamond() int32 {
	if x != nil {
		return x.CostDiamond
	}
	return 0
}

func (x *GachaBanner) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type GetGachaBannersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGachaBannersRequest) Reset() {
	*x = GetGachaBannersRequest{}
	mi := &file_gacha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGachaBannersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGachaBannersRequest) ProtoMessage() {}

func (x *GetGachaBannersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gacha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGachaBannersRequest.ProtoReflect.Descriptor instead.
func (*GetGachaBannersRequest) Descriptor() ([]byte, []int) {
	return file_gacha_proto_rawDescGZIP(), []int{1}
}

type GetGachaBannersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"` // C# đang tìm .Base
	Banners       []*GachaBanner         `protobuf:"bytes,2,rep,name=banners,proto3" json:"banners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGachaBannersResponse) Reset() {
	*x = GetGachaBannersResponse{}
	mi := &file_gacha_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGachaBannersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGachaBannersResponse) ProtoMessage() {}

func (x *GetGachaBannersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gacha_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGachaBannersResponse.ProtoReflect.Descriptor instead.
func (*GetGachaBannersResponse) Descriptor() ([]byte, []int) {
	return file_gacha_proto_rawDescGZIP(), []int{2}
}

func (x *GetGachaBannersResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetGachaBannersResponse) GetBanners() []*GachaBanner {
	if x != nil {
		return x.Banners
	}
	return nil
}

type DoGachaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BannerId      int32                  `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoGachaRequest) Reset() {
	*x = DoGachaRequest{}
	mi := &file_gacha_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoGachaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoGachaRequest) ProtoMessage() {}

func (x *DoGachaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gacha_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoGachaRequest.ProtoReflect.Descriptor instead.
func (*DoGachaRequest) Descriptor() ([]byte, []int) {
	return file_gacha_proto_rawDescGZIP(), []int{3}
}

func (x *DoGachaRequest) GetBannerId() int32 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

func (x *DoGachaRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DoGachaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                  // C# đang tìm .Base
	PlayerAfter   *PlayerProfile         `protobuf:"bytes,2,opt,name=player_after,json=playerAfter,proto3" json:"player_after,omitempty"` // C# đang tìm .PlayerAfter
	Heroes        []*Hero                `protobuf:"bytes,3,rep,name=heroes,proto3" json:"heroes,omitempty"`                              // C# đang tìm .Heroes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoGachaResponse) Reset() {
	*x = DoGachaResponse{}
	mi := &file_gacha_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoGachaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoGachaResponse) ProtoMessage() {}

func (x *DoGachaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gacha_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoGachaResponse.ProtoReflect.Descriptor instead.
func (*DoGachaResponse) Descriptor() ([]byte, []int) {
	return file_gacha_proto_rawDescGZIP(), []int{4}
}

func (x *DoGachaResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DoGachaResponse) GetPlayerAfter() *PlayerProfile {
	if x != nil {
		return x.PlayerAfter
	}
	return nil
}

func (x *DoGachaResponse) GetHeroes() []*Hero {
	if x != nil {
		return x.Heroes
	}
	return nil
}

var File_gacha_proto protoreflect.FileDescriptor

const file_gacha_proto_rawDesc = "" +
	"\n" +
	"\vgacha.proto\x12\x02pb\x1a\fcommon.proto\x1a\x0edisciple.proto\x1a\fplayer.proto\"\x9e\x01\n" +
	"\vGachaBanner\x12\x1b\n" +
	"\tbanner_id\x18\x01 \x01(\x05R\bbannerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fcost_diamond\x18\x04 \x01(\x05R\vcostDiamond\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\"\x18\n" +
	"\x16GetGachaBannersRequest\"j\n" +
	"\x17GetGachaBannersResponse\x12$\n" +
	"\x04base\x18\x01 \x01(\v2\x10.pb.BaseResponseR\x04base\x12)\n" +
	"\abanners\x18\x02 \x03(\v2\x0f.pb.GachaBannerR\abanners\"C\n" +
	"\x0eDoGachaRequest\x12\x1b\n" +
	"\tbanner_id\x18\x01 \x01(\x05R\bbannerId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x8f\x01\n" +
	"\x0fDoGachaResponse\x12$\n" +
	"\x04base\x18\x01 \x01(\v2\x10.pb.BaseResponseR\x04base\x124\n" +
	"\fplayer_after\x18\x02 \x01(\v2\x11.pb.PlayerProfileR\vplayerAfter\x12 \n" +
	"\x06heroes\x18\x03 \x03(\v2\b.pb.HeroR\x06heroesB*Z\x10server/pkg/pb;pb\xaa\x02\x15GameClient.Network.Pbb\x06proto3"

var (
	file_gacha_proto_rawDescOnce sync.Once
	file_gacha_proto_rawDescData []byte
)

func file_gacha_proto_rawDescGZIP() []byte {
	file_gacha_proto_rawDescOnce.Do(func() {
		file_gacha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gacha_proto_rawDesc), len(file_gacha_proto_rawDesc)))
	})
	return file_gacha_proto_rawDescData
}

var file_gacha_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gacha_proto_goTypes = []any{
	(*GachaBanner)(nil),             // 0: pb.GachaBanner
	(*GetGachaBannersRequest)(nil),  // 1: pb.GetGachaBannersRequest
	(*GetGachaBannersResponse)(nil), // 2: pb.GetGachaBannersResponse
	(*DoGachaRequest)(nil),          // 3: pb.DoGachaRequest
	(*DoGachaResponse)(nil),         // 4: pb.DoGachaResponse
	(*BaseResponse)(nil),            // 5: pb.BaseResponse
	(*PlayerProfile)(nil),           // 6: pb.PlayerProfile
	(*Hero)(nil),                    // 7: pb.Hero
}
var file_gacha_proto_depIdxs = []int32{
	5, // 0: pb.GetGachaBannersResponse.base:type_name -> pb.BaseResponse
	0, // 1: pb.GetGachaBannersResponse.banners:type_name -> pb.GachaBanner
	5, // 2: pb.DoGachaResponse.base:type_name -> pb.BaseResponse
	6, // 3: pb.DoGachaResponse.player_after:type_name -> pb.PlayerProfile
	7, // 4: pb.DoGachaResponse.heroes:type_name -> pb.Hero
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gacha_proto_init() }
func file_gacha_proto_init() {
	if File_gacha_proto != nil {
		return
	}
	file_common_proto_init()
	file_disciple_proto_init()
	file_player_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gacha_proto_rawDesc), len(file_gacha_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gacha_proto_goTypes,
		DependencyIndexes: file_gacha_proto_depIdxs,
		MessageInfos:      file_gacha_proto_msgTypes,
	}.Build()
	File_gacha_proto = out.File
	file_gacha_proto_goTypes = nil
	file_gacha_proto_depIdxs = nil
}
