// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: item.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabelKey      string                 `protobuf:"bytes,1,opt,name=label_key,json=labelKey,proto3" json:"label_key,omitempty"`    // Key cho tên nguồn (VD: "SOURCE_BLACKSMITH")
	InnerLink     string                 `protobuf:"bytes,2,opt,name=inner_link,json=innerLink,proto3" json:"inner_link,omitempty"` // Đường dẫn DeepLink (VD: "building/blacksmith")
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemSource) Reset() {
	*x = ItemSource{}
	mi := &file_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSource) ProtoMessage() {}

func (x *ItemSource) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSource.ProtoReflect.Descriptor instead.
func (*ItemSource) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{0}
}

func (x *ItemSource) GetLabelKey() string {
	if x != nil {
		return x.LabelKey
	}
	return ""
}

func (x *ItemSource) GetInnerLink() string {
	if x != nil {
		return x.InnerLink
	}
	return ""
}

func (x *ItemSource) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ItemSource) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type ItemEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EffectCode    string                 `protobuf:"bytes,1,opt,name=effect_code,json=effectCode,proto3" json:"effect_code,omitempty"` // "EFF_ADD_HP", "EFF_LIFESTEAL"
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`                           // Giá trị (VD: 10, 0.05)
	MinValue      float32                `protobuf:"fixed32,3,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`     // Giá trị tối thiểu (VD: 0)
	MaxValue      float32                `protobuf:"fixed32,4,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`     // Giá trị tối đa (VD: 1000)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemEffect) Reset() {
	*x = ItemEffect{}
	mi := &file_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemEffect) ProtoMessage() {}

func (x *ItemEffect) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemEffect.ProtoReflect.Descriptor instead.
func (*ItemEffect) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{1}
}

func (x *ItemEffect) GetEffectCode() string {
	if x != nil {
		return x.EffectCode
	}
	return ""
}

func (x *ItemEffect) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ItemEffect) GetMinValue() float32 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *ItemEffect) GetMaxValue() float32 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

type ItemConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemCode      string                 `protobuf:"bytes,1,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty"`
	NameKey       string                 `protobuf:"bytes,2,opt,name=name_key,json=nameKey,proto3" json:"name_key,omitempty"` // Thay thế name -> name_key
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Rarity        string                 `protobuf:"bytes,4,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	DescKey       string                 `protobuf:"bytes,6,opt,name=desc_key,json=descKey,proto3" json:"desc_key,omitempty"` // Thay thế description -> desc_key
	MaxStack      int32                  `protobuf:"varint,7,opt,name=max_stack,json=maxStack,proto3" json:"max_stack,omitempty"`
	Sources       []*ItemSource          `protobuf:"bytes,8,rep,name=sources,proto3" json:"sources,omitempty"`
	Effects       []*ItemEffect          `protobuf:"bytes,9,rep,name=effects,proto3" json:"effects,omitempty"` // Hiệu ứng dạng List
	RequiredLevel int32                  `protobuf:"varint,10,opt,name=required_level,json=requiredLevel,proto3" json:"required_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemConfig) Reset() {
	*x = ItemConfig{}
	mi := &file_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemConfig) ProtoMessage() {}

func (x *ItemConfig) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemConfig.ProtoReflect.Descriptor instead.
func (*ItemConfig) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{2}
}

func (x *ItemConfig) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *ItemConfig) GetNameKey() string {
	if x != nil {
		return x.NameKey
	}
	return ""
}

func (x *ItemConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ItemConfig) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *ItemConfig) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ItemConfig) GetDescKey() string {
	if x != nil {
		return x.DescKey
	}
	return ""
}

func (x *ItemConfig) GetMaxStack() int32 {
	if x != nil {
		return x.MaxStack
	}
	return 0
}

func (x *ItemConfig) GetSources() []*ItemSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ItemConfig) GetEffects() []*ItemEffect {
	if x != nil {
		return x.Effects
	}
	return nil
}

func (x *ItemConfig) GetRequiredLevel() int32 {
	if x != nil {
		return x.RequiredLevel
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                 // Instance ID (duy nhất cho từng item trong túi đồ)
	ItemCode      string                 `protobuf:"bytes,2,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty"`                                                      // Mã item để liên kết với ItemConfig
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                                              // (Có thể bỏ nếu dùng name từ Config, nhưng giữ lại cho trang bị có tiền tố random)
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`                                                                              // (Có thể bỏ nếu dùng type từ Config)
	Rarity        string                 `protobuf:"bytes,5,opt,name=rarity,proto3" json:"rarity,omitempty"`                                                                          // (Có thể bỏ nếu dùng rarity từ Config)
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`                                                                     // Số lượng (Dùng cho stackable)
	Stats         map[string]int32       `protobuf:"bytes,7,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Chỉ số cộng thêm nếu là trang bị
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{3}
}

func (x *Item) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Item) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *Item) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Item) GetStats() map[string]int32 {
	if x != nil {
		return x.Stats
	}
	return nil
}

type Inventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Configs       []*ItemConfig          `protobuf:"bytes,2,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{4}
}

func (x *Inventory) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Inventory) GetConfigs() []*ItemConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type EquipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiscipleId    int64                  `protobuf:"varint,1,opt,name=disciple_id,json=discipleId,proto3" json:"disciple_id,omitempty"`
	ItemId        int64                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // ID của item trong túi đồ
	Slot          string                 `protobuf:"bytes,3,opt,name=slot,proto3" json:"slot,omitempty"`                    // 'weapon', 'armor', 'accessory'
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipRequest) Reset() {
	*x = EquipRequest{}
	mi := &file_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipRequest) ProtoMessage() {}

func (x *EquipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipRequest.ProtoReflect.Descriptor instead.
func (*EquipRequest) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{5}
}

func (x *EquipRequest) GetDiscipleId() int64 {
	if x != nil {
		return x.DiscipleId
	}
	return 0
}

func (x *EquipRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *EquipRequest) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

type EquipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	EquippedItem  *Item                  `protobuf:"bytes,3,opt,name=equipped_item,json=equippedItem,proto3" json:"equipped_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipResponse) Reset() {
	*x = EquipResponse{}
	mi := &file_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipResponse) ProtoMessage() {}

func (x *EquipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipResponse.ProtoReflect.Descriptor instead.
func (*EquipResponse) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{6}
}

func (x *EquipResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EquipResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EquipResponse) GetEquippedItem() *Item {
	if x != nil {
		return x.EquippedItem
	}
	return nil
}

type Recipe struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecipeId       string                 `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	ResultItemCode string                 `protobuf:"bytes,2,opt,name=result_item_code,json=resultItemCode,proto3" json:"result_item_code,omitempty"`
	Materials      map[string]int32       `protobuf:"bytes,3,rep,name=materials,proto3" json:"materials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // item_code -> quantity
	SuccessRate    int32                  `protobuf:"varint,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`                                                    // % thành công
	CraftingTime   int32                  `protobuf:"varint,5,opt,name=crafting_time,json=craftingTime,proto3" json:"crafting_time,omitempty"`                                                 // Giây
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Recipe) Reset() {
	*x = Recipe{}
	mi := &file_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipe) ProtoMessage() {}

func (x *Recipe) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipe.ProtoReflect.Descriptor instead.
func (*Recipe) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{7}
}

func (x *Recipe) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *Recipe) GetResultItemCode() string {
	if x != nil {
		return x.ResultItemCode
	}
	return ""
}

func (x *Recipe) GetMaterials() map[string]int32 {
	if x != nil {
		return x.Materials
	}
	return nil
}

func (x *Recipe) GetSuccessRate() int32 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *Recipe) GetCraftingTime() int32 {
	if x != nil {
		return x.CraftingTime
	}
	return 0
}

type CraftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      string                 `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CraftRequest) Reset() {
	*x = CraftRequest{}
	mi := &file_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CraftRequest) ProtoMessage() {}

func (x *CraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CraftRequest.ProtoReflect.Descriptor instead.
func (*CraftRequest) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{8}
}

func (x *CraftRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *CraftRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CraftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	GainedItems   []*Item                `protobuf:"bytes,3,rep,name=gained_items,json=gainedItems,proto3" json:"gained_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CraftResponse) Reset() {
	*x = CraftResponse{}
	mi := &file_item_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CraftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CraftResponse) ProtoMessage() {}

func (x *CraftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CraftResponse.ProtoReflect.Descriptor instead.
func (*CraftResponse) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{9}
}

func (x *CraftResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CraftResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *CraftResponse) GetGainedItems() []*Item {
	if x != nil {
		return x.GainedItems
	}
	return nil
}

type UseItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // Instance ID of the item in player inventory
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`           // Quantity to use
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseItemRequest) Reset() {
	*x = UseItemRequest{}
	mi := &file_item_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemRequest) ProtoMessage() {}

func (x *UseItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemRequest.ProtoReflect.Descriptor instead.
func (*UseItemRequest) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{10}
}

func (x *UseItemRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *UseItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UseItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                           // 0: Success, other: error code
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // Response message ID (for i18n)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseItemResponse) Reset() {
	*x = UseItemResponse{}
	mi := &file_item_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemResponse) ProtoMessage() {}

func (x *UseItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemResponse.ProtoReflect.Descriptor instead.
func (*UseItemResponse) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{11}
}

func (x *UseItemResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UseItemResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

var File_item_proto protoreflect.FileDescriptor

const file_item_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"item.proto\x12\x02pb\x1a\fcommon.proto\"\x82\x01\n" +
	"\n" +
	"ItemSource\x12\x1b\n" +
	"\tlabel_key\x18\x01 \x01(\tR\blabelKey\x12\x1d\n" +
	"\n" +
	"inner_link\x18\x02 \x01(\tR\tinnerLink\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\"}\n" +
	"\n" +
	"ItemEffect\x12\x1f\n" +
	"\veffect_code\x18\x01 \x01(\tR\n" +
	"effectCode\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\x12\x1b\n" +
	"\tmin_value\x18\x03 \x01(\x02R\bminValue\x12\x1b\n" +
	"\tmax_value\x18\x04 \x01(\x02R\bmaxValue\"\xb7\x02\n" +
	"\n" +
	"ItemConfig\x12\x1b\n" +
	"\titem_code\x18\x01 \x01(\tR\bitemCode\x12\x19\n" +
	"\bname_key\x18\x02 \x01(\tR\anameKey\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06rarity\x18\x04 \x01(\tR\x06rarity\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x19\n" +
	"\bdesc_key\x18\x06 \x01(\tR\adescKey\x12\x1b\n" +
	"\tmax_stack\x18\a \x01(\x05R\bmaxStack\x12(\n" +
	"\asources\x18\b \x03(\v2\x0e.pb.ItemSourceR\asources\x12(\n" +
	"\aeffects\x18\t \x03(\v2\x0e.pb.ItemEffectR\aeffects\x12%\n" +
	"\x0erequired_level\x18\n" +
	" \x01(\x05R\rrequiredLevel\"\xf4\x01\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\titem_code\x18\x02 \x01(\tR\bitemCode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06rarity\x18\x05 \x01(\tR\x06rarity\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x12)\n" +
	"\x05stats\x18\a \x03(\v2\x13.pb.Item.StatsEntryR\x05stats\x1a8\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"U\n" +
	"\tInventory\x12\x1e\n" +
	"\x05items\x18\x01 \x03(\v2\b.pb.ItemR\x05items\x12(\n" +
	"\aconfigs\x18\x02 \x03(\v2\x0e.pb.ItemConfigR\aconfigs\"\\\n" +
	"\fEquipRequest\x12\x1f\n" +
	"\vdisciple_id\x18\x01 \x01(\x03R\n" +
	"discipleId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x03R\x06itemId\x12\x12\n" +
	"\x04slot\x18\x03 \x01(\tR\x04slot\"q\n" +
	"\rEquipResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12-\n" +
	"\requipped_item\x18\x03 \x01(\v2\b.pb.ItemR\fequippedItem\"\x8e\x02\n" +
	"\x06Recipe\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\tR\brecipeId\x12(\n" +
	"\x10result_item_code\x18\x02 \x01(\tR\x0eresultItemCode\x127\n" +
	"\tmaterials\x18\x03 \x03(\v2\x19.pb.Recipe.MaterialsEntryR\tmaterials\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x05R\vsuccessRate\x12#\n" +
	"\rcrafting_time\x18\x05 \x01(\x05R\fcraftingTime\x1a<\n" +
	"\x0eMaterialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"A\n" +
	"\fCraftRequest\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\tR\brecipeId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"o\n" +
	"\rCraftResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12+\n" +
	"\fgained_items\x18\x03 \x03(\v2\b.pb.ItemR\vgainedItems\"E\n" +
	"\x0eUseItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"D\n" +
	"\x0fUseItemResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageIdB*Z\x10server/pkg/pb;pb\xaa\x02\x15GameClient.Network.Pbb\x06proto3"

var (
	file_item_proto_rawDescOnce sync.Once
	file_item_proto_rawDescData []byte
)

func file_item_proto_rawDescGZIP() []byte {
	file_item_proto_rawDescOnce.Do(func() {
		file_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_proto_rawDesc), len(file_item_proto_rawDesc)))
	})
	return file_item_proto_rawDescData
}

var file_item_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_item_proto_goTypes = []any{
	(*ItemSource)(nil),      // 0: pb.ItemSource
	(*ItemEffect)(nil),      // 1: pb.ItemEffect
	(*ItemConfig)(nil),      // 2: pb.ItemConfig
	(*Item)(nil),            // 3: pb.Item
	(*Inventory)(nil),       // 4: pb.Inventory
	(*EquipRequest)(nil),    // 5: pb.EquipRequest
	(*EquipResponse)(nil),   // 6: pb.EquipResponse
	(*Recipe)(nil),          // 7: pb.Recipe
	(*CraftRequest)(nil),    // 8: pb.CraftRequest
	(*CraftResponse)(nil),   // 9: pb.CraftResponse
	(*UseItemRequest)(nil),  // 10: pb.UseItemRequest
	(*UseItemResponse)(nil), // 11: pb.UseItemResponse
	nil,                     // 12: pb.Item.StatsEntry
	nil,                     // 13: pb.Recipe.MaterialsEntry
}
var file_item_proto_depIdxs = []int32{
	0,  // 0: pb.ItemConfig.sources:type_name -> pb.ItemSource
	1,  // 1: pb.ItemConfig.effects:type_name -> pb.ItemEffect
	12, // 2: pb.Item.stats:type_name -> pb.Item.StatsEntry
	3,  // 3: pb.Inventory.items:type_name -> pb.Item
	2,  // 4: pb.Inventory.configs:type_name -> pb.ItemConfig
	3,  // 5: pb.EquipResponse.equipped_item:type_name -> pb.Item
	13, // 6: pb.Recipe.materials:type_name -> pb.Recipe.MaterialsEntry
	3,  // 7: pb.CraftResponse.gained_items:type_name -> pb.Item
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_item_proto_init() }
func file_item_proto_init() {
	if File_item_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_proto_rawDesc), len(file_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_item_proto_goTypes,
		DependencyIndexes: file_item_proto_depIdxs,
		MessageInfos:      file_item_proto_msgTypes,
	}.Build()
	File_item_proto = out.File
	file_item_proto_goTypes = nil
	file_item_proto_depIdxs = nil
}
