// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: world.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_world_proto protoreflect.FileDescriptor

const file_world_proto_rawDesc = "" +
	"\n" +
	"\vworld.proto\x12\x02pb\x1a\fcommon.proto\x1a\fplayer.proto\x1a\n" +
	"sect.proto\x1a\x0edisciple.proto\x1a\n" +
	"item.proto\x1a\vgacha.proto\x1a\rmission.proto\x1a\fcombat.proto\x1a\fsystem.proto\x1a\x11leaderboard.proto2\xe7\r\n" +
	"\x0eGatewayService\x12;\n" +
	"\n" +
	"GetVersion\x12\x15.pb.GetVersionRequest\x1a\x16.pb.GetVersionResponse\x122\n" +
	"\aGetBase\x12\x12.pb.GetBaseRequest\x1a\x13.pb.GetBaseResponse\x12A\n" +
	"\fCreatePlayer\x12\x17.pb.CreatePlayerRequest\x1a\x18.pb.CreatePlayerResponse\x12M\n" +
	"\x10GetPlayerProfile\x12\x1b.pb.GetPlayerProfileRequest\x1a\x1c.pb.GetPlayerProfileResponse\x122\n" +
	"\vGetSectInfo\x12\x15.pb.GetProfileRequest\x1a\f.pb.SectInfo\x12J\n" +
	"\x0fUpgradeBuilding\x12\x1a.pb.UpgradeBuildingRequest\x1a\x1b.pb.UpgradeBuildingResponse\x12J\n" +
	"\x0fSpeedUpBuilding\x12\x1a.pb.SpeedUpBuildingRequest\x1a\x1b.pb.SpeedUpBuildingResponse\x12M\n" +
	"\x10CollectResources\x12\x1b.pb.CollectResourcesRequest\x1a\x1c.pb.CollectResourcesResponse\x12A\n" +
	"\fSaveAdminMap\x12\x17.pb.SaveAdminMapRequest\x1a\x18.pb.SaveAdminMapResponse\x12A\n" +
	"\fGetPlayerMap\x12\x17.pb.GetPlayerMapRequest\x1a\x18.pb.GetPlayerMapResponse\x12D\n" +
	"\rSavePlayerMap\x12\x18.pb.SavePlayerMapRequest\x1a\x19.pb.SavePlayerMapResponse\x128\n" +
	"\tGetHeroes\x12\x14.pb.GetHeroesRequest\x1a\x15.pb.GetHeroesResponse\x12A\n" +
	"\fSetFormation\x12\x17.pb.SetFormationRequest\x1a\x18.pb.SetFormationResponse\x12J\n" +
	"\x0fLevelUpDisciple\x12\x1a.pb.LevelUpDiscipleRequest\x1a\x1b.pb.LevelUpDiscipleResponse\x12>\n" +
	"\vLevelUpHero\x12\x16.pb.LevelUpHeroRequest\x1a\x17.pb.LevelUpHeroResponse\x12A\n" +
	"\fCheckInDaily\x12\x17.pb.CheckInDailyRequest\x1a\x18.pb.CheckInDailyResponse\x12S\n" +
	"\x12ClaimMissionReward\x12\x1d.pb.ClaimMissionRewardRequest\x1a\x1e.pb.ClaimMissionRewardResponse\x12P\n" +
	"\x11ValidatePvEResult\x12\x1c.pb.ValidatePvEResultRequest\x1a\x1d.pb.ValidatePvEResultResponse\x124\n" +
	"\fGetInventory\x12\x15.pb.GetProfileRequest\x1a\r.pb.Inventory\x120\n" +
	"\tEquipItem\x12\x10.pb.EquipRequest\x1a\x11.pb.EquipResponse\x122\n" +
	"\aUseItem\x12\x12.pb.UseItemRequest\x1a\x13.pb.UseItemResponse\x12J\n" +
	"\x0fGetGachaBanners\x12\x1a.pb.GetGachaBannersRequest\x1a\x1b.pb.GetGachaBannersResponse\x122\n" +
	"\aDoGacha\x12\x12.pb.DoGachaRequest\x1a\x13.pb.DoGachaResponse\x12>\n" +
	"\vGetMissions\x12\x16.pb.GetMissionsRequest\x1a\x17.pb.GetMissionsResponse\x12S\n" +
	"\x12GetCompletedStages\x12\x1d.pb.GetCompletedStagesRequest\x1a\x1e.pb.GetCompletedStagesResponse\x12G\n" +
	"\x0eGetLeaderboard\x12\x19.pb.GetLeaderboardRequest\x1a\x1a.pb.GetLeaderboardResponse2\xf4\x01\n" +
	"\fWorldService\x122\n" +
	"\x10InternalSyncSect\x12\f.pb.SectInfo\x1a\x10.pb.BaseResponse\x12<\n" +
	"\rListCutscenes\x12\x10.pb.EmptyRequest\x1a\x19.pb.ListCutscenesResponse\x127\n" +
	"\vGetCutscene\x12\x16.pb.GetCutsceneRequest\x1a\x10.pb.CutsceneData\x129\n" +
	"\fSaveCutscene\x12\x17.pb.SaveCutsceneRequest\x1a\x10.pb.BaseResponseB*Z\x10server/pkg/pb;pb\xaa\x02\x15GameClient.Network.Pbb\x06proto3"

var file_world_proto_goTypes = []any{
	(*GetVersionRequest)(nil),          // 0: pb.GetVersionRequest
	(*GetBaseRequest)(nil),             // 1: pb.GetBaseRequest
	(*CreatePlayerRequest)(nil),        // 2: pb.CreatePlayerRequest
	(*GetPlayerProfileRequest)(nil),    // 3: pb.GetPlayerProfileRequest
	(*GetProfileRequest)(nil),          // 4: pb.GetProfileRequest
	(*UpgradeBuildingRequest)(nil),     // 5: pb.UpgradeBuildingRequest
	(*SpeedUpBuildingRequest)(nil),     // 6: pb.SpeedUpBuildingRequest
	(*CollectResourcesRequest)(nil),    // 7: pb.CollectResourcesRequest
	(*SaveAdminMapRequest)(nil),        // 8: pb.SaveAdminMapRequest
	(*GetPlayerMapRequest)(nil),        // 9: pb.GetPlayerMapRequest
	(*SavePlayerMapRequest)(nil),       // 10: pb.SavePlayerMapRequest
	(*GetHeroesRequest)(nil),           // 11: pb.GetHeroesRequest
	(*SetFormationRequest)(nil),        // 12: pb.SetFormationRequest
	(*LevelUpDiscipleRequest)(nil),     // 13: pb.LevelUpDiscipleRequest
	(*LevelUpHeroRequest)(nil),         // 14: pb.LevelUpHeroRequest
	(*CheckInDailyRequest)(nil),        // 15: pb.CheckInDailyRequest
	(*ClaimMissionRewardRequest)(nil),  // 16: pb.ClaimMissionRewardRequest
	(*ValidatePvEResultRequest)(nil),   // 17: pb.ValidatePvEResultRequest
	(*EquipRequest)(nil),               // 18: pb.EquipRequest
	(*UseItemRequest)(nil),             // 19: pb.UseItemRequest
	(*GetGachaBannersRequest)(nil),     // 20: pb.GetGachaBannersRequest
	(*DoGachaRequest)(nil),             // 21: pb.DoGachaRequest
	(*GetMissionsRequest)(nil),         // 22: pb.GetMissionsRequest
	(*GetCompletedStagesRequest)(nil),  // 23: pb.GetCompletedStagesRequest
	(*GetLeaderboardRequest)(nil),      // 24: pb.GetLeaderboardRequest
	(*SectInfo)(nil),                   // 25: pb.SectInfo
	(*EmptyRequest)(nil),               // 26: pb.EmptyRequest
	(*GetCutsceneRequest)(nil),         // 27: pb.GetCutsceneRequest
	(*SaveCutsceneRequest)(nil),        // 28: pb.SaveCutsceneRequest
	(*GetVersionResponse)(nil),         // 29: pb.GetVersionResponse
	(*GetBaseResponse)(nil),            // 30: pb.GetBaseResponse
	(*CreatePlayerResponse)(nil),       // 31: pb.CreatePlayerResponse
	(*GetPlayerProfileResponse)(nil),   // 32: pb.GetPlayerProfileResponse
	(*UpgradeBuildingResponse)(nil),    // 33: pb.UpgradeBuildingResponse
	(*SpeedUpBuildingResponse)(nil),    // 34: pb.SpeedUpBuildingResponse
	(*CollectResourcesResponse)(nil),   // 35: pb.CollectResourcesResponse
	(*SaveAdminMapResponse)(nil),       // 36: pb.SaveAdminMapResponse
	(*GetPlayerMapResponse)(nil),       // 37: pb.GetPlayerMapResponse
	(*SavePlayerMapResponse)(nil),      // 38: pb.SavePlayerMapResponse
	(*GetHeroesResponse)(nil),          // 39: pb.GetHeroesResponse
	(*SetFormationResponse)(nil),       // 40: pb.SetFormationResponse
	(*LevelUpDiscipleResponse)(nil),    // 41: pb.LevelUpDiscipleResponse
	(*LevelUpHeroResponse)(nil),        // 42: pb.LevelUpHeroResponse
	(*CheckInDailyResponse)(nil),       // 43: pb.CheckInDailyResponse
	(*ClaimMissionRewardResponse)(nil), // 44: pb.ClaimMissionRewardResponse
	(*ValidatePvEResultResponse)(nil),  // 45: pb.ValidatePvEResultResponse
	(*Inventory)(nil),                  // 46: pb.Inventory
	(*EquipResponse)(nil),              // 47: pb.EquipResponse
	(*UseItemResponse)(nil),            // 48: pb.UseItemResponse
	(*GetGachaBannersResponse)(nil),    // 49: pb.GetGachaBannersResponse
	(*DoGachaResponse)(nil),            // 50: pb.DoGachaResponse
	(*GetMissionsResponse)(nil),        // 51: pb.GetMissionsResponse
	(*GetCompletedStagesResponse)(nil), // 52: pb.GetCompletedStagesResponse
	(*GetLeaderboardResponse)(nil),     // 53: pb.GetLeaderboardResponse
	(*BaseResponse)(nil),               // 54: pb.BaseResponse
	(*ListCutscenesResponse)(nil),      // 55: pb.ListCutscenesResponse
	(*CutsceneData)(nil),               // 56: pb.CutsceneData
}
var file_world_proto_depIdxs = []int32{
	0,  // 0: pb.GatewayService.GetVersion:input_type -> pb.GetVersionRequest
	1,  // 1: pb.GatewayService.GetBase:input_type -> pb.GetBaseRequest
	2,  // 2: pb.GatewayService.CreatePlayer:input_type -> pb.CreatePlayerRequest
	3,  // 3: pb.GatewayService.GetPlayerProfile:input_type -> pb.GetPlayerProfileRequest
	4,  // 4: pb.GatewayService.GetSectInfo:input_type -> pb.GetProfileRequest
	5,  // 5: pb.GatewayService.UpgradeBuilding:input_type -> pb.UpgradeBuildingRequest
	6,  // 6: pb.GatewayService.SpeedUpBuilding:input_type -> pb.SpeedUpBuildingRequest
	7,  // 7: pb.GatewayService.CollectResources:input_type -> pb.CollectResourcesRequest
	8,  // 8: pb.GatewayService.SaveAdminMap:input_type -> pb.SaveAdminMapRequest
	9,  // 9: pb.GatewayService.GetPlayerMap:input_type -> pb.GetPlayerMapRequest
	10, // 10: pb.GatewayService.SavePlayerMap:input_type -> pb.SavePlayerMapRequest
	11, // 11: pb.GatewayService.GetHeroes:input_type -> pb.GetHeroesRequest
	12, // 12: pb.GatewayService.SetFormation:input_type -> pb.SetFormationRequest
	13, // 13: pb.GatewayService.LevelUpDisciple:input_type -> pb.LevelUpDiscipleRequest
	14, // 14: pb.GatewayService.LevelUpHero:input_type -> pb.LevelUpHeroRequest
	15, // 15: pb.GatewayService.CheckInDaily:input_type -> pb.CheckInDailyRequest
	16, // 16: pb.GatewayService.ClaimMissionReward:input_type -> pb.ClaimMissionRewardRequest
	17, // 17: pb.GatewayService.ValidatePvEResult:input_type -> pb.ValidatePvEResultRequest
	4,  // 18: pb.GatewayService.GetInventory:input_type -> pb.GetProfileRequest
	18, // 19: pb.GatewayService.EquipItem:input_type -> pb.EquipRequest
	19, // 20: pb.GatewayService.UseItem:input_type -> pb.UseItemRequest
	20, // 21: pb.GatewayService.GetGachaBanners:input_type -> pb.GetGachaBannersRequest
	21, // 22: pb.GatewayService.DoGacha:input_type -> pb.DoGachaRequest
	22, // 23: pb.GatewayService.GetMissions:input_type -> pb.GetMissionsRequest
	23, // 24: pb.GatewayService.GetCompletedStages:input_type -> pb.GetCompletedStagesRequest
	24, // 25: pb.GatewayService.GetLeaderboard:input_type -> pb.GetLeaderboardRequest
	25, // 26: pb.WorldService.InternalSyncSect:input_type -> pb.SectInfo
	26, // 27: pb.WorldService.ListCutscenes:input_type -> pb.EmptyRequest
	27, // 28: pb.WorldService.GetCutscene:input_type -> pb.GetCutsceneRequest
	28, // 29: pb.WorldService.SaveCutscene:input_type -> pb.SaveCutsceneRequest
	29, // 30: pb.GatewayService.GetVersion:output_type -> pb.GetVersionResponse
	30, // 31: pb.GatewayService.GetBase:output_type -> pb.GetBaseResponse
	31, // 32: pb.GatewayService.CreatePlayer:output_type -> pb.CreatePlayerResponse
	32, // 33: pb.GatewayService.GetPlayerProfile:output_type -> pb.GetPlayerProfileResponse
	25, // 34: pb.GatewayService.GetSectInfo:output_type -> pb.SectInfo
	33, // 35: pb.GatewayService.UpgradeBuilding:output_type -> pb.UpgradeBuildingResponse
	34, // 36: pb.GatewayService.SpeedUpBuilding:output_type -> pb.SpeedUpBuildingResponse
	35, // 37: pb.GatewayService.CollectResources:output_type -> pb.CollectResourcesResponse
	36, // 38: pb.GatewayService.SaveAdminMap:output_type -> pb.SaveAdminMapResponse
	37, // 39: pb.GatewayService.GetPlayerMap:output_type -> pb.GetPlayerMapResponse
	38, // 40: pb.GatewayService.SavePlayerMap:output_type -> pb.SavePlayerMapResponse
	39, // 41: pb.GatewayService.GetHeroes:output_type -> pb.GetHeroesResponse
	40, // 42: pb.GatewayService.SetFormation:output_type -> pb.SetFormationResponse
	41, // 43: pb.GatewayService.LevelUpDisciple:output_type -> pb.LevelUpDiscipleResponse
	42, // 44: pb.GatewayService.LevelUpHero:output_type -> pb.LevelUpHeroResponse
	43, // 45: pb.GatewayService.CheckInDaily:output_type -> pb.CheckInDailyResponse
	44, // 46: pb.GatewayService.ClaimMissionReward:output_type -> pb.ClaimMissionRewardResponse
	45, // 47: pb.GatewayService.ValidatePvEResult:output_type -> pb.ValidatePvEResultResponse
	46, // 48: pb.GatewayService.GetInventory:output_type -> pb.Inventory
	47, // 49: pb.GatewayService.EquipItem:output_type -> pb.EquipResponse
	48, // 50: pb.GatewayService.UseItem:output_type -> pb.UseItemResponse
	49, // 51: pb.GatewayService.GetGachaBanners:output_type -> pb.GetGachaBannersResponse
	50, // 52: pb.GatewayService.DoGacha:output_type -> pb.DoGachaResponse
	51, // 53: pb.GatewayService.GetMissions:output_type -> pb.GetMissionsResponse
	52, // 54: pb.GatewayService.GetCompletedStages:output_type -> pb.GetCompletedStagesResponse
	53, // 55: pb.GatewayService.GetLeaderboard:output_type -> pb.GetLeaderboardResponse
	54, // 56: pb.WorldService.InternalSyncSect:output_type -> pb.BaseResponse
	55, // 57: pb.WorldService.ListCutscenes:output_type -> pb.ListCutscenesResponse
	56, // 58: pb.WorldService.GetCutscene:output_type -> pb.CutsceneData
	54, // 59: pb.WorldService.SaveCutscene:output_type -> pb.BaseResponse
	30, // [30:60] is the sub-list for method output_type
	0,  // [0:30] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_world_proto_init() }
func file_world_proto_init() {
	if File_world_proto != nil {
		return
	}
	file_common_proto_init()
	file_player_proto_init()
	file_sect_proto_init()
	file_disciple_proto_init()
	file_item_proto_init()
	file_gacha_proto_init()
	file_mission_proto_init()
	file_combat_proto_init()
	file_system_proto_init()
	file_leaderboard_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_world_proto_rawDesc), len(file_world_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_world_proto_goTypes,
		DependencyIndexes: file_world_proto_depIdxs,
	}.Build()
	File_world_proto = out.File
	file_world_proto_goTypes = nil
	file_world_proto_depIdxs = nil
}
